# Introdcution to scikit-learn 
## This notebook demonstrates some of the good functions in the scikit-learn library
### what we are going to cover
#### 0 An end to end scikit-learn workflow
#### 1 Getting the data ready
#### 2 Choose the right estimator/algorithm for our problem.
#### 3 Fit the model/algorithm and use it to make predictions on our data
#### 4 Evaluating a model
#### 5 Improve a model
#### 6 save and load trained model
#### 7 Putting it all together !

## 0 An end to end scikit-learn workflow

In [90]:
# standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [35]:
# 1. get the data ready
import numpy as np
import pandas as pd
heart_disease = pd.read_csv("./data/heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [9]:
# create x (features matrix)
x = heart_disease.drop("target",axis=1)

# create y (labels)
y = heart_disease["target"]

In [23]:
# 2 Choose the right model and hyperparameters
from sklearn.ensemble  import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# we'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [36]:
# Fit the model to the training data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

clf.fit(x_train,y_train)

RandomForestClassifier()

In [43]:
y_preds = clf.predict(x_test)
y_preds

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1])

In [44]:
y_test

204    0
275    0
265    0
138    1
70     1
      ..
66     1
15     1
258    0
172    0
7      1
Name: target, Length: 61, dtype: int64

In [45]:
# 4 Evaluate the model on training data and test data
clf.score(x_train,y_train)

1.0

In [46]:
clf.score(x_test,y_test)

0.8360655737704918

In [51]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [53]:
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.77      0.83      0.80        24
           1       0.89      0.84      0.86        37

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61

In [56]:
confusion_matrix(y_test,y_preds)

array([[20,  4],
       [ 6, 31]])

In [57]:
accuracy_score(y_test,y_preds)

0.8360655737704918

In [73]:
#5 Improve a model
# try different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators")
    clf=RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"Model accuracy on test set: {clf.score(x_test,y_test)*100:.2f}%")
    print("")

Trying model with 10 estimators
Model accuracy on test set: 70.49%

Trying model with 20 estimators
Model accuracy on test set: 78.69%

Trying model with 30 estimators
Model accuracy on test set: 77.05%

Trying model with 40 estimators
Model accuracy on test set: 81.97%

Trying model with 50 estimators
Model accuracy on test set: 78.69%

Trying model with 60 estimators
Model accuracy on test set: 80.33%

Trying model with 70 estimators
Model accuracy on test set: 83.61%

Trying model with 80 estimators
Model accuracy on test set: 81.97%

Trying model with 90 estimators
Model accuracy on test set: 85.25%

In [81]:
# 6 Save a model and load it
import pickle
pickle.dump(clf, open("random_forest_model_1.pkl","wb"))

In [84]:
loaded_model = pickle.load(open("random_forest_model_1.pkl","rb"))

In [86]:
loaded_model.score(x_test,y_test)

0.8524590163934426

In [89]:
import sklearn
sklearn.__version__

'1.6.1'

# 1. Getting our data ready to be used with ML

Three main things we have to do
 1. Split the data into features and labels (usually `x` & `y`)
 2. Filling (alos called imputing) or disregarding missing values
 3. Converting non-numerical values to numerical values (aka Feature encoding)

In [91]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [92]:
x = heart_disease.drop("target",axis=1)
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [95]:
y=heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [104]:
# split the data intp training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [107]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [112]:
x.shape

(303, 13)

In [114]:
x.shape[0] * 0.8  # 80%

242.4

In [116]:
x.shape[0] * .2

60.6

In [115]:
242+61  # 61 = 20%

303

In [109]:
len(heart_disease)

303

In [99]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3
222,65,1,3,138,282,1,0,174,0,1.4,1,1,2
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1
86,68,1,2,118,277,0,1,151,0,1.0,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1
131,49,0,1,134,271,0,1,162,0,0.0,1,0,2
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2

In [100]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3
194,60,1,2,140,185,0,0,155,0,3.0,1,0,2
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,54,0,1,132,288,1,0,159,1,0.0,2,1,2
44,39,1,2,140,321,0,0,182,0,0.0,2,0,2
48,53,0,2,128,216,0,0,115,0,0.0,2,0,0
115,37,0,2,120,215,0,1,170,0,0.0,2,0,2
250,51,1,0,140,298,0,1,122,1,4.2,1,3,3

In [101]:
y_train

240    0
222    0
293    0
297    0
86     1
      ..
291    0
131    1
300    0
216    0
144    1
Name: target, Length: 227, dtype: int64

In [102]:
y_test

220    0
194    0
30     1
295    0
294    0
      ..
93     1
44     1
48     1
115    1
250    0
Name: target, Length: 76, dtype: int64